### ISSUE TITLE
Installation fails at roles/bahmni-erp/tasks/main.yml

### ISSUE THREAD

**Issue by andreis** [Bahmni/bahmni-playbooks#5]
Trying to install on a fresh CentOS (64 bit, 6.8) in VirtualBox. Any help would be appreciated.

```TASK [bahmni-erp : Install bahmni-erp from bahmni-repo] ************************
task path: /opt/bahmni-installer/bahmni-playbooks/roles/bahmni-erp/tasks/main.yml:47
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Error: Package: bahmni-erp-0.89-49.noarch (bahmni)\n           Requires: mx\n", "rc": 1, "results": ["Loaded plugins: fastestmirror, refresh-packagekit, security\nSetting up Install Process\nLoading mirror speeds from cached hostfile\n * base: ro-bucharest-repo.bigstepcloud.com\n * epel: mirror.atomki.mta.hu\n * extras: ro-bucharest-repo.bigstepcloud.com\n * updates: ro-bucharest-repo.bigstepcloud.com\nResolving Dependencies\n--> Running transaction check\n---> Package bahmni-erp.noarch 0:0.89-49 will be installed\n--> Processing Dependency: python-feedparser for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-mock for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-unittest2 for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: pywebdav for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: byacc for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: kernel-devel for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: gcc-c++ for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: gcc for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: automake for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-docutils for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-psutil for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: glade3 for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-vatnumber for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-openid for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-vobject for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-imaging for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-reportlab for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: pydot for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: pychart for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-dateutil for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: python-matplotlib for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: libxslt-python for package: bahmni-erp-0.89-49.noarch\n--> Processing Dependency: PyXML for package: bahmni-erp-0.89-49.noarch\n--> Running transaction check\n---> Package PyXML.x86_64 0:0.8.4-19.el6 will be installed\n---> Package automake.noarch 0:1.11.1-4.el6 will be installed\n--> Processing Dependency: autoconf >= 2.62 for package: automake-1.11.1-4.el6.noarch\n---> Package bahmni-erp.noarch 0:0.89-49 will be installed\n--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch\n---> Package byacc.x86_64 0:1.9.20070509-7.el6 will be installed\n---> Package gcc.x86_64 0:4.4.7-18.el6 will be installed\n--> Processing Dependency: libgomp = 4.4.7-18.el6 for package: gcc-4.4.7-18.el6.x86_64\n--> Processing Dependency: cpp = 4.4.7-18.el6 for package: gcc-4.4.7-18.el6.x86_64\n--> Processing Dependency: libgcc >= 4.4.7-18.el6 for package: gcc-4.4.7-18.el6.x86_64\n--> Processing Dependency: cloog-ppl >= 0.15 for package: gcc-4.4.7-18.el6.x86_64\n---> Package gcc-c++.x86_64 0:4.4.7-18.el6 will be installed\n--> Processing Dependency: libstdc++-devel = 4.4.7-18.el6 for package: gcc-c++-4.4.7-18.el6.x86_64\n--> Processing Dependency: libstdc++ = 4.4.7-18.el6 for package: gcc-c++-4.4.7-18.el6.x86_64\n--> Processing Dependency: libmpfr.so.1()(64bit) for package: gcc-c++-4.4.7-18.el6.x86_64\n---> Package glade3.x86_64 0:3.6.7-2.1.el6 will be installed\n--> Processing Dependency: glade3-libgladeui = 3.6.7-2.1.el6 for package: glade3-3.6.7-2.1.el6.x86_64\n--> Processing Dependency: libgladeui-1.so.9()(64bit) for package: glade3-3.6.7-2.1.el6.x86_64\n---> Package kernel-devel.x86_64 0:2.6.32-696.10.3.el6 will be installed\n---> Package libxslt-python.x86_64 0:1.1.26-2.el6_3.1 will be installed\n---> Package pychart.noarch 0:1.39-10.1.el6 will be installed\n---> Package pydot.noarch 0:1.0.3-1.el6 will be installed\n--> Processing Dependency: pyparsing for package: pydot-1.0.3-1.el6.noarch\n--> Processing Dependency: graphviz for package: pydot-1.0.3-1.el6.noarch\n---> Package python-dateutil.noarch 0:1.4.1-7.el6 will be installed\n---> Package python-docutils.noarch 0:0.6-1.el6 will be installed\n---> Package python-feedparser.noarch 0:5.1.2-2.el6 will be installed\n---> Package python-imaging.x86_64 0:1.1.6-19.el6 will be installed\n---> Package python-matplotlib.x86_64 0:0.99.1.2-1.el6 will be installed\n--> Processing Dependency: pytz for package: python-matplotlib-0.99.1.2-1.el6.x86_64\n---> Package python-openid.noarch 0:2.2.5-7.el6 will be installed\n---> Package python-psutil.x86_64 0:0.6.1-1.el6 will be installed\n---> Package python-reportlab.x86_64 0:2.3-3.el6 will be installed\n---> Package python-unittest2.noarch 0:0.5.1-3.el6 will be installed\n---> Package python-vatnumber.noarch 0:1.0-1.el6 will be installed\n--> Processing Dependency: python-suds for package: python-vatnumber-1.0-1.el6.noarch\n---> Package python-vobject.noarch 0:0.8.1c-5.el6 will be installed\n---> Package python2-mock.noarch 0:1.0.1-10.el6 will be installed\n---> Package pywebdav.noarch 0:0.9.4.1-1.el6 will be installed\n--> Running transaction check\n---> Package autoconf.noarch 0:2.63-5.1.el6 will be installed\n---> Package bahmni-erp.noarch 0:0.89-49 will be installed\n--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch\n---> Package cloog-ppl.x86_64 0:0.15.7-1.2.el6 will be installed\n--> Processing Dependency: libppl_c.so.2()(64bit) for package: cloog-ppl-0.15.7-1.2.el6.x86_64\n--> Processing Dependency: libppl.so.7()(64bit) for package: cloog-ppl-0.15.7-1.2.el6.x86_64\n---> Package cpp.x86_64 0:4.4.7-18.el6 will be installed\n---> Package glade3-libgladeui.x86_64 0:3.6.7-2.1.el6 will be installed\n--> Processing Dependency: devhelp for package: glade3-libgladeui-3.6.7-2.1.el6.x86_64\n---> Package graphviz.x86_64 0:2.26.0-10.el6 will be installed\n--> Processing Dependency: libgd.so.2()(64bit) for package: graphviz-2.26.0-10.el6.x86_64\n---> Package libgcc.x86_64 0:4.4.7-17.el6 will be updated\n---> Package libgcc.x86_64 0:4.4.7-18.el6 will be an update\n---> Package libgomp.x86_64 0:4.4.7-17.el6 will be updated\n---> Package libgomp.x86_64 0:4.4.7-18.el6 will be an update\n---> Package libstdc++.x86_64 0:4.4.7-17.el6 will be updated\n---> Package libstdc++.x86_64 0:4.4.7-18.el6 will be an update\n---> Package libstdc++-devel.x86_64 0:4.4.7-18.el6 will be installed\n---> Package mpfr.x86_64 0:2.4.1-6.el6 will be installed\n---> Package pyparsing.noarch 0:1.5.6-1.el6 will be installed\n---> Package python-suds.noarch 0:0.4.1-3.el6 will be installed\n---> Package pytz.noarch 0:2010h-2.el6 will be installed\n--> Running transaction check\n---> Package bahmni-erp.noarch 0:0.89-49 will be installed\n--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch\n---> Package devhelp.x86_64 0:2.28.1-6.el6 will be installed\n---> Package gd.x86_64 0:2.0.35-11.el6 will be installed\n---> Package ppl.x86_64 0:0.10.2-11.el6 will be installed\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
	to retry, use: --limit @/opt/bahmni-installer/bahmni-playbooks/all.retry

PLAY RECAP *********************************************************************
localhost                  : ok=173  changed=61   unreachable=0    failed=1

Traceback (most recent call last):
  File "/usr/bin/bahmni", line 9, in <module>
    load_entry_point('bahmni==0.1', 'console_scripts', 'bahmni')()
  File "/usr/lib/python2.6/site-packages/click-6.7-py2.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click-6.7-py2.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click-6.7-py2.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click-6.7-py2.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click-6.7-py2.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click-6.7-py2.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/bahmni-0.1-py2.6.egg/bahmni.py", line 91, in install
    return subprocess.check_call(command, shell=True)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ansible-playbook -i /etc/bahmni-installer/local all.yml -vv  --extra-vars '@/etc/bahmni-installer/rpm_versions.yml' --extra-vars '@/etc/bahmni-backrest.conf' --extra-vars '@/etc/bahmni-installer/setup.yml'' returned non-zero exit status 2```

**Comment by andreis** [comment]
Easier to read:

```
Error: Package: bahmni-erp-0.89-49.noarch (bahmni)
           Requires: mx
", "rc": 1, "results": ["Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ro-bucharest-repo.bigstepcloud.com
 * epel: fedora.mirrors.telekom.ro
 * extras: ro-bucharest-repo.bigstepcloud.com
 * updates: ro-bucharest-repo.bigstepcloud.com
Resolving Dependencies
--> Running transaction check
---> Package bahmni-erp.noarch 0:0.89-49 will be installed
--> Processing Dependency: python-feedparser for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-mock for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-unittest2 for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: pywebdav for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: byacc for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: kernel-devel for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: gcc-c++ for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: gcc for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: automake for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-docutils for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-psutil for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: glade3 for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-vatnumber for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-openid for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-vobject for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-imaging for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-reportlab for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: pydot for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: pychart for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-dateutil for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: python-matplotlib for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: libxslt-python for package: bahmni-erp-0.89-49.noarch
--> Processing Dependency: PyXML for package: bahmni-erp-0.89-49.noarch
--> Running transaction check
---> Package PyXML.x86_64 0:0.8.4-19.el6 will be installed
---> Package automake.noarch 0:1.11.1-4.el6 will be installed
--> Processing Dependency: autoconf >= 2.62 for package: automake-1.11.1-4.el6.noarch
---> Package bahmni-erp.noarch 0:0.89-49 will be installed
--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch
---> Package byacc.x86_64 0:1.9.20070509-7.el6 will be installed
---> Package gcc.x86_64 0:4.4.7-18.el6 will be installed
--> Processing Dependency: libgomp = 4.4.7-18.el6 for package: gcc-4.4.7-18.el6.x86_64
--> Processing Dependency: cpp = 4.4.7-18.el6 for package: gcc-4.4.7-18.el6.x86_64
--> Processing Dependency: libgcc >= 4.4.7-18.el6 for package: gcc-4.4.7-18.el6.x86_64
--> Processing Dependency: cloog-ppl >= 0.15 for package: gcc-4.4.7-18.el6.x86_64
---> Package gcc-c++.x86_64 0:4.4.7-18.el6 will be installed
--> Processing Dependency: libstdc++-devel = 4.4.7-18.el6 for package: gcc-c++-4.4.7-18.el6.x86_64
--> Processing Dependency: libstdc++ = 4.4.7-18.el6 for package: gcc-c++-4.4.7-18.el6.x86_64
--> Processing Dependency: libmpfr.so.1()(64bit) for package: gcc-c++-4.4.7-18.el6.x86_64
---> Package glade3.x86_64 0:3.6.7-2.1.el6 will be installed
--> Processing Dependency: glade3-libgladeui = 3.6.7-2.1.el6 for package: glade3-3.6.7-2.1.el6.x86_64
--> Processing Dependency: libgladeui-1.so.9()(64bit) for package: glade3-3.6.7-2.1.el6.x86_64
---> Package kernel-devel.x86_64 0:2.6.32-696.10.3.el6 will be installed
---> Package libxslt-python.x86_64 0:1.1.26-2.el6_3.1 will be installed
---> Package pychart.noarch 0:1.39-10.1.el6 will be installed
---> Package pydot.noarch 0:1.0.3-1.el6 will be installed
--> Processing Dependency: pyparsing for package: pydot-1.0.3-1.el6.noarch
--> Processing Dependency: graphviz for package: pydot-1.0.3-1.el6.noarch
---> Package python-dateutil.noarch 0:1.4.1-7.el6 will be installed
---> Package python-docutils.noarch 0:0.6-1.el6 will be installed
---> Package python-feedparser.noarch 0:5.1.2-2.el6 will be installed
---> Package python-imaging.x86_64 0:1.1.6-19.el6 will be installed
---> Package python-matplotlib.x86_64 0:0.99.1.2-1.el6 will be installed
--> Processing Dependency: pytz for package: python-matplotlib-0.99.1.2-1.el6.x86_64
---> Package python-openid.noarch 0:2.2.5-7.el6 will be installed
---> Package python-psutil.x86_64 0:0.6.1-1.el6 will be installed
---> Package python-reportlab.x86_64 0:2.3-3.el6 will be installed
---> Package python-unittest2.noarch 0:0.5.1-3.el6 will be installed
---> Package python-vatnumber.noarch 0:1.0-1.el6 will be installed
--> Processing Dependency: python-suds for package: python-vatnumber-1.0-1.el6.noarch
---> Package python-vobject.noarch 0:0.8.1c-5.el6 will be installed
---> Package python2-mock.noarch 0:1.0.1-10.el6 will be installed
---> Package pywebdav.noarch 0:0.9.4.1-1.el6 will be installed
--> Running transaction check
---> Package autoconf.noarch 0:2.63-5.1.el6 will be installed
---> Package bahmni-erp.noarch 0:0.89-49 will be installed
--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch
---> Package cloog-ppl.x86_64 0:0.15.7-1.2.el6 will be installed
--> Processing Dependency: libppl_c.so.2()(64bit) for package: cloog-ppl-0.15.7-1.2.el6.x86_64
--> Processing Dependency: libppl.so.7()(64bit) for package: cloog-ppl-0.15.7-1.2.el6.x86_64
---> Package cpp.x86_64 0:4.4.7-18.el6 will be installed
---> Package glade3-libgladeui.x86_64 0:3.6.7-2.1.el6 will be installed
--> Processing Dependency: devhelp for package: glade3-libgladeui-3.6.7-2.1.el6.x86_64
---> Package graphviz.x86_64 0:2.26.0-10.el6 will be installed
--> Processing Dependency: libgd.so.2()(64bit) for package: graphviz-2.26.0-10.el6.x86_64
---> Package libgcc.x86_64 0:4.4.7-17.el6 will be updated
---> Package libgcc.x86_64 0:4.4.7-18.el6 will be an update
---> Package libgomp.x86_64 0:4.4.7-17.el6 will be updated
---> Package libgomp.x86_64 0:4.4.7-18.el6 will be an update
---> Package libstdc++.x86_64 0:4.4.7-17.el6 will be updated
---> Package libstdc++.x86_64 0:4.4.7-18.el6 will be an update
---> Package libstdc++-devel.x86_64 0:4.4.7-18.el6 will be installed
---> Package mpfr.x86_64 0:2.4.1-6.el6 will be installed
---> Package pyparsing.noarch 0:1.5.6-1.el6 will be installed
---> Package python-suds.noarch 0:0.4.1-3.el6 will be installed
---> Package pytz.noarch 0:2010h-2.el6 will be installed
--> Running transaction check
---> Package bahmni-erp.noarch 0:0.89-49 will be installed
--> Processing Dependency: mx for package: bahmni-erp-0.89-49.noarch
---> Package devhelp.x86_64 0:2.28.1-6.el6 will be installed
---> Package gd.x86_64 0:2.0.35-11.el6 will be installed
---> Package ppl.x86_64 0:0.10.2-11.el6 will be installed
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by binduak** [comment]
Hi @andreis,
There is [this](https://bahmni.atlassian.net/browse/BAH-40) defect card created to fix the issue. This will be available in the next Bahmni release. Meanwhile you can follow the steps mentioned in the card to resolve the issue. You can also follow [Bahmni talk](talk.bahmni.org) forum for more question/answers. Thank you.

Regards,
Bindu

**Comment by andreis** [comment]
That's great, thank you Bindu! 👍
